language: python
cache: pip
sudo: false
python:
  - "pypy2.7-5.9.0"
  - "pypy3.5-5.9.0"
  - "2.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "nightly"
services:
  - memcached
  - redis-server
# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install flake8 pytest-cov '.[tests]'"
# command to run tests
script:
  - "flake8 --ignore=E501,E999 ring tests setup.py"
  - "py.test --cov=ring -vv tests/"
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - python: "nightly"
